# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

comb_nparC <- function(mcmcout) {
    .Call('irtpar_comb_nparC', PACKAGE = 'irtpar', mcmcout)
}

