# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.m_conv <- function(x) {
    .Call('irtpar_m_conv', PACKAGE = 'irtpar', x)
}

.v_conv <- function(x) {
    .Call('irtpar_v_conv', PACKAGE = 'irtpar', x)
}

.v_conv1 <- function(x) {
    .Call('irtpar_v_conv1', PACKAGE = 'irtpar', x)
}

.nv_mean <- function(x) {
    .Call('irtpar_nv_mean', PACKAGE = 'irtpar', x)
}

dmvnrm_arma <- function(x_i, mean_i, sigma_i, logd = FALSE) {
    .Call('irtpar_dmvnrm_arma', PACKAGE = 'irtpar', x_i, mean_i, sigma_i, logd)
}

mvrnorm_arma <- function(n, mu, sigma) {
    .Call('irtpar_mvrnorm_arma', PACKAGE = 'irtpar', n, mu, sigma)
}

.theta_bar <- function(t, post_list, h, d, M) {
    .Call('irtpar_theta_bar', PACKAGE = 'irtpar', t, post_list, h, d, M)
}

.mix_weight <- function(t, post_list, h, d, M) {
    .Call('irtpar_mix_weight', PACKAGE = 'irtpar', t, post_list, h, d, M)
}

.vcm <- function(X_i) {
    .Call('irtpar_vcm', PACKAGE = 'irtpar', X_i)
}

post_vcm <- function(post_list) {
    .Call('irtpar_post_vcm', PACKAGE = 'irtpar', post_list)
}

post_mean <- function(post_list, post_vcm) {
    .Call('irtpar_post_mean', PACKAGE = 'irtpar', post_list, post_vcm)
}

#' Non-parametric Combination of Sub-posteriors
#' 
#' @param post_list A list containing the sub-posterior samples, stored in matrices
#' @return A matrix containing the samples from the sub-posterior product function
combine_np <- function(post_list) {
    .Call('irtpar_combine_np', PACKAGE = 'irtpar', post_list)
}

