# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmvnrm_arma <- function(x, mean, sigma, out) {
    invisible(.Call('irtpar_dmvnrm_arma', PACKAGE = 'irtpar', x, mean, sigma, out))
}

mvrnorm_arma <- function(n, mu, sigma, out) {
    invisible(.Call('irtpar_mvrnorm_arma', PACKAGE = 'irtpar', n, mu, sigma, out))
}

post_vcm <- function(post_list, d, M, out) {
    invisible(.Call('irtpar_post_vcm', PACKAGE = 'irtpar', post_list, d, M, out))
}

post_mean <- function(post_list, post_vcm, d, M, out) {
    invisible(.Call('irtpar_post_mean', PACKAGE = 'irtpar', post_list, post_vcm, d, M, out))
}

.theta_bar <- function(t, post_list, h, d, M, out) {
    invisible(.Call('irtpar_theta_bar', PACKAGE = 'irtpar', t, post_list, h, d, M, out))
}

.mix_weight <- function(t, post_list, h, d, M, theta_b) {
    .Call('irtpar_mix_weight', PACKAGE = 'irtpar', t, post_list, h, d, M, theta_b)
}

#' Non-parametric Combination of Sub-posteriors
#' @param post_list A list containing the sub-posterior samples, stored in matrices
#' @return A matrix containing the samples from the sub-posterior product function
#' @export
combine_np <- function(post_list, out) {
    invisible(.Call('irtpar_combine_np', PACKAGE = 'irtpar', post_list, out))
}

.mix_weight_sp <- function(t, sig_M, mu_M, w_t_dot, post_list, h, d, M, post_means, post_vcms, theta_b, out) {
    invisible(.Call('irtpar_mix_weight_sp', PACKAGE = 'irtpar', t, sig_M, mu_M, w_t_dot, post_list, h, d, M, post_means, post_vcms, theta_b, out))
}

#' Semi-parametric Combination of Sub-posteriors
#' 
#' @param post_list A list containing the sub-posterior samples, stored in matrices
#' @return A matrix containing the samples from the sub-posterior product function
#' @export
combine_sp <- function(post_list, out) {
    invisible(.Call('irtpar_combine_sp', PACKAGE = 'irtpar', post_list, out))
}

